name: Pull Request Merge Video Link

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Display video link
      if: github.event.pull_request.merged == true
      run: echo " Please watch this video: https://www.youtube.com/watch?v=xvFZjo5PgG0"
